/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    implementation("org.knowm.xchart:xchart:3.8.0")

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    //mainClass = "org.example.AppKt"
    mainClass = "org.example.AppSequence"
}

// Extra task to run the App.kt version without changing the default mainClass
tasks.register<JavaExec>("runApp") {
    group = "application"
    description = "Run App (top-level main)."
    mainClass.set("org.example.AppKt")
    classpath = sourceSets["main"].runtimeClasspath
    // Pass 'obrigatorios' via project property, e.g., -Pobrigatorios="1,2,3"
    (project.findProperty("obrigatorios") as String?)?.let { args(it) }
}

// Extra task to run the AppSequence.kt version without changing the default mainClass
tasks.register<JavaExec>("runSeq") {
    group = "application"
    description = "Run AppSequence (streaming)."
    mainClass.set("org.example.AppSequence")
    classpath = sourceSets["main"].runtimeClasspath
    (project.findProperty("obrigatorios") as String?)?.let { args(it) }
}

// Extra task to run the TURB version without changing the default mainClass
tasks.register<JavaExec>("runTurb") {
    group = "application"
    description = "Run AppSequenceTurb (IntArray + GC events)."
    mainClass.set("org.example.AppSequenceTurb")
    classpath = sourceSets["main"].runtimeClasspath
    // Optional: fix heap size to reduce expansion noise
    jvmArgs = listOf("-Xms512m", "-Xmx512m")
    // Allow passing step interval via -PstepInterval=5000 (project property)
    val step = (project.findProperty("stepInterval") as String?) ?: "10000"
    args(step)
    // Optional obrigatórios list
    (project.findProperty("obrigatorios") as String?)?.let { args(it) }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
